// <auto-generated />
using System;
using Infra.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Infra.Database.models.AccountModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Infra.Database.models.AssetModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableQuantity = 201257220,
                            Name = "ALPARGATAS",
                            Price = 20.63m,
                            Symbol = "ALPA4"
                        },
                        new
                        {
                            Id = 3,
                            AvailableQuantity = 201257220,
                            Name = "AMBEV S/A",
                            Price = 14.51m,
                            Symbol = "ABEV3"
                        },
                        new
                        {
                            Id = 4,
                            AvailableQuantity = 596875824,
                            Name = "AMERICANAS",
                            Price = 15.93m,
                            Symbol = "AMER3"
                        },
                        new
                        {
                            Id = 5,
                            AvailableQuantity = 794531367,
                            Name = "ASSAI",
                            Price = 15.65m,
                            Symbol = "ASAI3"
                        },
                        new
                        {
                            Id = 6,
                            AvailableQuantity = 327741172,
                            Name = "AZUL",
                            Price = 11.58m,
                            Symbol = "AZUL4"
                        },
                        new
                        {
                            Id = 7,
                            AvailableQuantity = 327741172,
                            Name = "B3",
                            Price = 10.72m,
                            Symbol = "B3SA3"
                        },
                        new
                        {
                            Id = 8,
                            AvailableQuantity = 341124068,
                            Name = "BANCO PAN",
                            Price = 7.08m,
                            Symbol = "BPAN4"
                        },
                        new
                        {
                            Id = 9,
                            AvailableQuantity = 671629692,
                            Name = "BBSEGURIDADE",
                            Price = 27.88m,
                            Symbol = "BBSE3"
                        },
                        new
                        {
                            Id = 10,
                            AvailableQuantity = 828273884,
                            Name = "BR MALLS PAR",
                            Price = 7.82m,
                            Symbol = "BRML3"
                        },
                        new
                        {
                            Id = 11,
                            AvailableQuantity = 1516726535,
                            Name = "BRADESCO",
                            Price = 14.16m,
                            Symbol = "BBDC3"
                        },
                        new
                        {
                            Id = 12,
                            AvailableQuantity = 201257220,
                            Name = "BRADESCO",
                            Price = 17.05m,
                            Symbol = "BBDC4"
                        },
                        new
                        {
                            Id = 13,
                            AvailableQuantity = 251402249,
                            Name = "BRADESPAR",
                            Price = 22.33m,
                            Symbol = "BRAP4"
                        },
                        new
                        {
                            Id = 14,
                            AvailableQuantity = 1420530937,
                            Name = "BRASIL",
                            Price = 34.67m,
                            Symbol = "BBAS3"
                        },
                        new
                        {
                            Id = 15,
                            AvailableQuantity = 264975728,
                            Name = "BRASKEM",
                            Price = 34.08m,
                            Symbol = "BRKM5"
                        },
                        new
                        {
                            Id = 16,
                            AvailableQuantity = 1076512610,
                            Name = "BRF SA",
                            Price = 16.07m,
                            Symbol = "BRFS3"
                        },
                        new
                        {
                            Id = 17,
                            AvailableQuantity = 1301655996,
                            Name = "BTGP BANCO",
                            Price = 22.47m,
                            Symbol = "BPAC11"
                        },
                        new
                        {
                            Id = 18,
                            AvailableQuantity = 410988561,
                            Name = "CARREFOUR BR",
                            Price = 16.93m,
                            Symbol = "CRFB3"
                        },
                        new
                        {
                            Id = 19,
                            AvailableQuantity = 1115693556,
                            Name = "CCR SA",
                            Price = 12.28m,
                            Symbol = "CCRO3"
                        },
                        new
                        {
                            Id = 20,
                            AvailableQuantity = 1448479060,
                            Name = "CEMIG",
                            Price = 10.65m,
                            Symbol = "CMIG4"
                        },
                        new
                        {
                            Id = 21,
                            AvailableQuantity = 1144359228,
                            Name = "CIELO",
                            Price = 4.08m,
                            Symbol = "CIEL3"
                        },
                        new
                        {
                            Id = 22,
                            AvailableQuantity = 1828106676,
                            Name = "COGNA ON",
                            Price = 2.22m,
                            Symbol = "COGN3"
                        },
                        new
                        {
                            Id = 23,
                            AvailableQuantity = 1563365506,
                            Name = "COPEL",
                            Price = 6.9m,
                            Symbol = "CPLE6"
                        },
                        new
                        {
                            Id = 24,
                            AvailableQuantity = 1171063698,
                            Name = "COSAN",
                            Price = 17.49m,
                            Symbol = "CSAN3"
                        },
                        new
                        {
                            Id = 25,
                            AvailableQuantity = 187732538,
                            Name = "CPFL ENERGIA",
                            Price = 32.14m,
                            Symbol = "CPFE3"
                        },
                        new
                        {
                            Id = 26,
                            AvailableQuantity = 1120593365,
                            Name = "CSNMINERACAO",
                            Price = 3.4m,
                            Symbol = "CMIN3"
                        },
                        new
                        {
                            Id = 27,
                            AvailableQuantity = 276543929,
                            Name = "CVC BRASIL",
                            Price = 6.76m,
                            Symbol = "CVCB3"
                        },
                        new
                        {
                            Id = 28,
                            AvailableQuantity = 281609283,
                            Name = "CYRELA REALT",
                            Price = 12.26m,
                            Symbol = "CYRE3"
                        },
                        new
                        {
                            Id = 29,
                            AvailableQuantity = 295712871,
                            Name = "DEXCO",
                            Price = 9.71m,
                            Symbol = "DXCO3"
                        },
                        new
                        {
                            Id = 30,
                            AvailableQuantity = 339237914,
                            Name = "ECORODOVIAS",
                            Price = 5.4m,
                            Symbol = "ECOR3"
                        },
                        new
                        {
                            Id = 31,
                            AvailableQuantity = 985704248,
                            Name = "ELETROBRAS",
                            Price = 44.63m,
                            Symbol = "ELET3"
                        },
                        new
                        {
                            Id = 32,
                            AvailableQuantity = 242987127,
                            Name = "ELETROBRAS",
                            Price = 45.67m,
                            Symbol = "ELET6"
                        },
                        new
                        {
                            Id = 33,
                            AvailableQuantity = 734588205,
                            Name = "EMBRAER",
                            Price = 11.87m,
                            Symbol = "EMBR3"
                        },
                        new
                        {
                            Id = 34,
                            AvailableQuantity = 230931405,
                            Name = "ENERGIAS BR",
                            Price = 21.29m,
                            Symbol = "ENBR3"
                        },
                        new
                        {
                            Id = 35,
                            AvailableQuantity = 248477689,
                            Name = "ENERGISA",
                            Price = 40.65m,
                            Symbol = "ENGI11"
                        },
                        new
                        {
                            Id = 36,
                            AvailableQuantity = 1557479978,
                            Name = "ENEVA",
                            Price = 14.35m,
                            Symbol = "ENEV3"
                        },
                        new
                        {
                            Id = 37,
                            AvailableQuantity = 255217329,
                            Name = "ENGIE BRASIL",
                            Price = 42.17m,
                            Symbol = "EGIE3"
                        },
                        new
                        {
                            Id = 38,
                            AvailableQuantity = 1100513485,
                            Name = "EQUATORIAL",
                            Price = 23.05m,
                            Symbol = "EQTL3"
                        },
                        new
                        {
                            Id = 39,
                            AvailableQuantity = 101618236,
                            Name = "EZTEC",
                            Price = 16.37m,
                            Symbol = "EZTC3"
                        },
                        new
                        {
                            Id = 40,
                            AvailableQuantity = 303373882,
                            Name = "FLEURY",
                            Price = 15.27m,
                            Symbol = "FLRY3"
                        },
                        new
                        {
                            Id = 41,
                            AvailableQuantity = 1097534498,
                            Name = "GERDAU",
                            Price = 23.81m,
                            Symbol = "GGBR4"
                        },
                        new
                        {
                            Id = 42,
                            AvailableQuantity = 698275321,
                            Name = "GERDAU MET",
                            Price = 9.94m,
                            Symbol = "GOAU4"
                        },
                        new
                        {
                            Id = 43,
                            AvailableQuantity = 167095214,
                            Name = "GOL",
                            Price = 7.97m,
                            Symbol = "GOLL4"
                        },
                        new
                        {
                            Id = 44,
                            AvailableQuantity = 834914221,
                            Name = "GRUPO NATURA",
                            Price = 15.84m,
                            Symbol = "NTCO3"
                        },
                        new
                        {
                            Id = 45,
                            AvailableQuantity = 489316435,
                            Name = "GRUPO SOMA",
                            Price = 9.77m,
                            Symbol = "SOMA3"
                        },
                        new
                        {
                            Id = 46,
                            AvailableQuantity = 201257220,
                            Name = "HAPVIDA",
                            Price = 5.95m,
                            Symbol = "HAPV3"
                        },
                        new
                        {
                            Id = 47,
                            AvailableQuantity = 410253528,
                            Name = "HYPERA",
                            Price = 39.93m,
                            Symbol = "HYPE3"
                        },
                        new
                        {
                            Id = 48,
                            AvailableQuantity = 180013980,
                            Name = "IGUATEMI SA",
                            Price = 18.87m,
                            Symbol = "IGTI11"
                        },
                        new
                        {
                            Id = 49,
                            AvailableQuantity = 1255286531,
                            Name = "IRBBRASIL RE",
                            Price = 2m,
                            Symbol = "IRBR3"
                        },
                        new
                        {
                            Id = 50,
                            AvailableQuantity = 201257220,
                            Name = "ITAUSA",
                            Price = 8.47m,
                            Symbol = "ITSA4"
                        },
                        new
                        {
                            Id = 51,
                            AvailableQuantity = 201257220,
                            Name = "ITAUUNIBANCO",
                            Price = 23.26m,
                            Symbol = "ITUB4"
                        },
                        new
                        {
                            Id = 52,
                            AvailableQuantity = 1290736673,
                            Name = "JBS",
                            Price = 30.73m,
                            Symbol = "JBSS3"
                        },
                        new
                        {
                            Id = 53,
                            AvailableQuantity = 305915142,
                            Name = "JHSF PART",
                            Price = 5.6m,
                            Symbol = "JHSF3"
                        },
                        new
                        {
                            Id = 54,
                            AvailableQuantity = 812994397,
                            Name = "KLABIN S/A",
                            Price = 18.9m,
                            Symbol = "KLBN11"
                        },
                        new
                        {
                            Id = 55,
                            AvailableQuantity = 735708470,
                            Name = "LOCALIZA",
                            Price = 55.42m,
                            Symbol = "RENT3"
                        },
                        new
                        {
                            Id = 56,
                            AvailableQuantity = 418965264,
                            Name = "LOCAWEB",
                            Price = 6.74m,
                            Symbol = "LWSA3"
                        },
                        new
                        {
                            Id = 57,
                            AvailableQuantity = 977821540,
                            Name = "LOJAS RENNER",
                            Price = 24.42m,
                            Symbol = "LREN3"
                        },
                        new
                        {
                            Id = 58,
                            AvailableQuantity = 201257220,
                            Name = "MAGAZ LUIZA",
                            Price = 2.86m,
                            Symbol = "MGLU3"
                        },
                        new
                        {
                            Id = 59,
                            AvailableQuantity = 348234011,
                            Name = "MARFRIG",
                            Price = 13.39m,
                            Symbol = "MRFG3"
                        },
                        new
                        {
                            Id = 60,
                            AvailableQuantity = 548153725,
                            Name = "MELIUZ",
                            Price = 1.08m,
                            Symbol = "CASH3"
                        },
                        new
                        {
                            Id = 61,
                            AvailableQuantity = 260409710,
                            Name = "MINERVA",
                            Price = 13.22m,
                            Symbol = "BEEF3"
                        },
                        new
                        {
                            Id = 62,
                            AvailableQuantity = 294647234,
                            Name = "MRV",
                            Price = 8.68m,
                            Symbol = "MRVE3"
                        },
                        new
                        {
                            Id = 63,
                            AvailableQuantity = 272718548,
                            Name = "MULTIPLAN",
                            Price = 23.98m,
                            Symbol = "MULT3"
                        },
                        new
                        {
                            Id = 64,
                            AvailableQuantity = 156946474,
                            Name = "PACUCAR-CBD",
                            Price = 16.9m,
                            Symbol = "PCAR3"
                        },
                        new
                        {
                            Id = 65,
                            AvailableQuantity = 201257220,
                            Name = "PETROBRAS",
                            Price = 31.93m,
                            Symbol = "PETR3"
                        },
                        new
                        {
                            Id = 66,
                            AvailableQuantity = 201257220,
                            Name = "PETROBRAS",
                            Price = 29.33m,
                            Symbol = "PETR4"
                        },
                        new
                        {
                            Id = 67,
                            AvailableQuantity = 839159130,
                            Name = "PETRORIO",
                            Price = 22.67m,
                            Symbol = "PRIO3"
                        },
                        new
                        {
                            Id = 68,
                            AvailableQuantity = 336154589,
                            Name = "PETZ",
                            Price = 9.87m,
                            Symbol = "PETZ3"
                        },
                        new
                        {
                            Id = 69,
                            AvailableQuantity = 78053723,
                            Name = "POSITIVO TEC",
                            Price = 6.64m,
                            Symbol = "POSI3"
                        },
                        new
                        {
                            Id = 70,
                            AvailableQuantity = 277027077,
                            Name = "QUALICORP",
                            Price = 10.43m,
                            Symbol = "QUAL3"
                        },
                        new
                        {
                            Id = 71,
                            AvailableQuantity = 1071076905,
                            Name = "RAIADROGASIL",
                            Price = 20.03m,
                            Symbol = "RADL3"
                        },
                        new
                        {
                            Id = 72,
                            AvailableQuantity = 772010260,
                            Name = "REDE D OR",
                            Price = 30.25m,
                            Symbol = "RDOR3"
                        },
                        new
                        {
                            Id = 73,
                            AvailableQuantity = 1216056103,
                            Name = "RUMO SA",
                            Price = 16.09m,
                            Symbol = "RAIL3"
                        },
                        new
                        {
                            Id = 74,
                            AvailableQuantity = 340001934,
                            Name = "SABESP",
                            Price = 43.55m,
                            Symbol = "SBSP3"
                        },
                        new
                        {
                            Id = 75,
                            AvailableQuantity = 362703399,
                            Name = "SANTANDER BR",
                            Price = 27.53m,
                            Symbol = "SANB11"
                        },
                        new
                        {
                            Id = 76,
                            AvailableQuantity = 642398790,
                            Name = "SID NACIONAL",
                            Price = 14.41m,
                            Symbol = "CSNA3"
                        },
                        new
                        {
                            Id = 77,
                            AvailableQuantity = 96270946,
                            Name = "SLC AGRICOLA",
                            Price = 42.35m,
                            Symbol = "SLCE3"
                        },
                        new
                        {
                            Id = 78,
                            AvailableQuantity = 283167854,
                            Name = "SUL AMERICA",
                            Price = 22.1m,
                            Symbol = "SULA11"
                        },
                        new
                        {
                            Id = 79,
                            AvailableQuantity = 726779281,
                            Name = "SUZANO SA",
                            Price = 46.91m,
                            Symbol = "SUZB3"
                        },
                        new
                        {
                            Id = 80,
                            AvailableQuantity = 218568234,
                            Name = "TAESA",
                            Price = 40.25m,
                            Symbol = "TAEE11"
                        },
                        new
                        {
                            Id = 81,
                            AvailableQuantity = 413890875,
                            Name = "TELEF BRASIL",
                            Price = 46.83m,
                            Symbol = "VIVT3"
                        },
                        new
                        {
                            Id = 82,
                            AvailableQuantity = 808619532,
                            Name = "TIM",
                            Price = 12.9m,
                            Symbol = "TIMS3"
                        },
                        new
                        {
                            Id = 83,
                            AvailableQuantity = 519851955,
                            Name = "TOTVS",
                            Price = 25.89m,
                            Symbol = "TOTS3"
                        },
                        new
                        {
                            Id = 84,
                            AvailableQuantity = 1086067887,
                            Name = "ULTRAPAR",
                            Price = 12.46m,
                            Symbol = "UGPA3"
                        },
                        new
                        {
                            Id = 85,
                            AvailableQuantity = 514680651,
                            Name = "USIMINAS",
                            Price = 8.91m,
                            Symbol = "USIM5"
                        },
                        new
                        {
                            Id = 86,
                            AvailableQuantity = 201257220,
                            Name = "VALE",
                            Price = 69.21m,
                            Symbol = "VALE3"
                        },
                        new
                        {
                            Id = 87,
                            AvailableQuantity = 1596295753,
                            Name = "VIA",
                            Price = 2.51m,
                            Symbol = "VIIA3"
                        },
                        new
                        {
                            Id = 88,
                            AvailableQuantity = 1131883365,
                            Name = "VIBRA",
                            Price = 16.54m,
                            Symbol = "VBBR3"
                        },
                        new
                        {
                            Id = 89,
                            AvailableQuantity = 1484859030,
                            Name = "WEG",
                            Price = 25.84m,
                            Symbol = "WEGE3"
                        },
                        new
                        {
                            Id = 90,
                            AvailableQuantity = 300833122,
                            Name = "YDUQS PART",
                            Price = 13.9m,
                            Symbol = "YDUQ3"
                        },
                        new
                        {
                            Id = 91,
                            AvailableQuantity = 200372163,
                            Name = "3R PETROLEUM",
                            Price = 29.43m,
                            Symbol = "RRRP3"
                        });
                });

            modelBuilder.Entity("Infra.Database.models.ClientModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Infra.Database.models.InvestmentsHistoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("InvestmentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AssetId");

                    b.ToTable("InvestmentsHistory");
                });

            modelBuilder.Entity("Infra.Database.models.PortfolioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("AcquisitionValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<decimal>("AveragePurchasePrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ProfitabilityPercentage")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ProfitabilityValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AssetId");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("Infra.Database.models.TransactionHistoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("TransactionHistory");
                });

            modelBuilder.Entity("Infra.Database.models.AccountModel", b =>
                {
                    b.HasOne("Infra.Database.models.ClientModel", "Client")
                        .WithOne("Account")
                        .HasForeignKey("Infra.Database.models.AccountModel", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Infra.Database.models.InvestmentsHistoryModel", b =>
                {
                    b.HasOne("Infra.Database.models.AccountModel", "Account")
                        .WithMany("InvestmentsHistory")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infra.Database.models.AssetModel", "Asset")
                        .WithMany("InvestmentsHistory")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Infra.Database.models.PortfolioModel", b =>
                {
                    b.HasOne("Infra.Database.models.AccountModel", "Account")
                        .WithMany("Portfolios")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infra.Database.models.AssetModel", "Asset")
                        .WithMany("Portfolios")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Infra.Database.models.TransactionHistoryModel", b =>
                {
                    b.HasOne("Infra.Database.models.AccountModel", "Account")
                        .WithMany("TransactionHistory")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Infra.Database.models.AccountModel", b =>
                {
                    b.Navigation("InvestmentsHistory");

                    b.Navigation("Portfolios");

                    b.Navigation("TransactionHistory");
                });

            modelBuilder.Entity("Infra.Database.models.AssetModel", b =>
                {
                    b.Navigation("InvestmentsHistory");

                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("Infra.Database.models.ClientModel", b =>
                {
                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
